### ISSUE TITLE
Make jump chars different color if the jump needs 2 chars

### ISSUE THREAD

**Issue by ruohola** [a690700752/KJump#10]
Would be nice if the color of the jump characters would be different (and also user configurable) if the jump needs 2 characters.

For example in Vim, with vim-easymotion if I only need one char for the jump it's bright red, and if I need 2 chars for the jump the first of those is orange and the 2nd one is brown.

Here's an example of how it looks with vim-easymotion:
![Example image](https://user-images.githubusercontent.com/33625218/53912514-c4d7e780-4061-11e9-83c3-3bb5964ca82c.png)

**Comment by ruohola** [comment]
Any update on this?

**Comment by a690700752** [comment]
Working on it.
