### ISSUE TITLE
Prioritise search keys

### ISSUE THREAD

**Issue by Chazmus** [a690700752/KJump#14]
Hello! thought it could be a cool idea to be able to set which search keys to include/prioritise - Such as the functionality in vim easymotion you can get by setting g:EasyMotion_keys

I find this useful as I can get better speed when sticking with home row keys/keys that my index fingers reach.

**Comment by a690700752** [comment]
You can find it in the settings.

**Comment by Chazmus** [comment]
So it is! Sorry, a very silly question!
